### PR TITLE
Add support to skipped notifications (from, to)

### PR DESCRIPTION
**Pull request by stronk7**
With HUBOT_JENKINS_SKIP_NOTIFICATION it's possible to specify
pairs of statuses (from , to) not leading to any notification.

### CODE REVIEW

**Comment by danpoltawski** [comment]
I remember thinking about adding something like this at the time!

**Comment by danpoltawski** [comment]
Merged, thanks Eloy

**Comment by danpoltawski** [comment]
I've published an updated version of the package to npm

**Comment by stronk7** [comment]
Yay, thanks!

**Pull request merged**
